[package]
name = "mindisplayinfo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
display-info = "0.5.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "s"   # Optimize for size.