# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile Linux
        id: compile-linux
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}
      - name: Compile Windows
        id: compile-windows
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-windows.outputs.BUILT_CHECKSUM }}